.github/workflows/gh-pages.yml, package-lock.json
Added github pages yaml for vuepress
Publishes to sanofi-iadc.github.io/whispr
=> Configure vuepress deploy

package-lock.json, package.json
This reverts commit b2eaca5f679d320e3a6894cac3a66091a75f0c50.
=> Revert "Update dependency fastify-compress to v2"

.vscode/settings.json, src/webhook/webhook.service.ts
**Please check if the PR fulfills these requirements**
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- Adds simple logging functionality for webhooks to show success or failure
- Also vscode setting to enter debug mode
**What is the current behavior?** (You can also link to an open issue here)
- There's no logging
**What is the new behavior (if this is a feature change)?**
- Before sending will show this in the log:
`
[Webhook] Trying to send webhook to https://mywebhook.com
`
- Webhook with response will show message like:
`
[Webhook] Webhook post response status: 200 | statusText: OK | url: https://mywebhook.com
`
- Webhook with error will print full error to log
**Does this PR introduce a breaking change?** (What changes might users need to make …
=> feat: added simple logging for webhook

src/config/environmentValidationSchema.ts
Bug fix
Config-Service does not return env-var CA_CERTIFICATE_PATH
Config-Service returns env-var CA_CERTIFICATE_PATH
NO
=> fix(webhook): added CA_CERTIFICATE_PATH to validationSchema

docker-compose.dev.yml, tests/e2e/webhook/webhook.e2e-spec.ts, tests/e2e/whisp/graphql.e2e-spec.ts
End to end tests on the Webhooks to ensure events are triggered when whisps are created/updated/deleted
=> test(webhooks): test webhooks trigger on whispr creation/updated/deletion

src/config/config.service.ts
Bug fix
Tunnel throws an error when there are self-signed certificates in pipeline
Flatten the array, so it contains an array of Buffer
No
=> fix(webhook): fixed ca-array in tunnel

docs/testing.md, tests/e2e/whisp/graphql.e2e-spec.ts
End to end tests updateWhisp and deleteWhisp mutation
=> test(whisps): test update and delete graphql mutations

tests/e2e/tagGroup/graphql.e2e-spec.ts
=> test(tag-group): test tagGroup graphQL endpoint

src/pubSub/pubSub.module.ts
Bugfix
Timestamps are not returned by subscriptions
Subscriptions return timestamp
No
=> fix(subscriptions): added parser to Redis to handle Dates

src/whisp/whisp.schema.ts
Allow to filter efficently and sort on type and timestamp field
You cannot sort the whisps on the timestamp currently and filter at the same time on the type of the whisp
=> fix(index): add compound index on timestamp and type

Dockerfile, docs/.vuepress/config.js, docs/apm.md, package-lock.json, package.json, src/main.ts
- Adds Instana dependencies and docker layer for Instana APM
- No Instana dependency
n/a
No
n/a
=> feat(instana): add instana config

.github/workflows/ci.yml, package-lock.json, package.json
- Bugfix to correct dependency errors and also add additional CI check
- The dev/test build was actually working, only the prod build was building, but it broke during the release stage where npm run build was actually executed
n/a
- Revert updated dependencies for apollo which were breaking the build
- Add npm run build into the quality step to add extra verification that the prod build will definitely work
* **Does this PR introduce a breaking change?** (What changes might users need to make in their …
=> fix: add prod build to CI quality workflow

src/app.typings.d.ts, tsconfig.json
Change in JSON module resolution. It should fix the breaking CI/CD process 
Currently the files are built in `dist/src` due to a recent change
The files are going to be built in `dist` folder 
It fixes breaking change
Please test locally before merging
=> fix(build): changes JSON module resolution

package-lock.json, package.json, src/config/config.service.ts, tests/unit/config/config.service.spec.ts
-  Optional configuration of a proxy when retrieving jwks
- When using a proxy calls to the jwt provider timeout
- No breaking changes
=> feat(auth): add proxy to jwks retrieval

tests/unit/config/config.service.spec.ts
- [] Tests for the changes have been added (for bug fixes / features)
- [] Docs have been added / updated (for bug fixes / features)
=> feat(auth): reset https proxy value for proxy test

docs/security.md, src/config/authConfig.ts, src/config/config.service.ts, src/config/environmentValidationSchema.ts, tests/testUtils/testingConsts.ts, tests/unit/config/config.service.spec.ts
feature
secret must be hardcoded in the AUTH_CONFIG_SECRET json conf
not easy to place sensible data
remplace secretOrKey by secretOrKeyFromKey and store the secret in another protected env variable
no
=> feat(auth): retrieving secret from env variable

docs/models/whisp.md
The branch add a new TimeToLive feature to Whispr
Currently TTL Feature doesn't exists
Creating a whisp with the timeToLive attribute make the whisp deleted afer the TTL times out
No breaking change. Only new field are added
this commit is a fix of the comment which was not semantic release compliant. The feature was not detected
=> feat(whisp): add timeToLive semantic release fix

.github/workflows/gh-pages.yml
Bug fix  docs publishing
docs publishing is failing during github action
docs publishing is shouldn't fail anymore
No
=> fix(docs): fix github action docs publish

src/config/config.service.ts
Change SSL configuration for mongoose 6.X.X
Error while launching whisper because of unrecognized attributes (deprecated)
Launch whispr with new mongoose configuration
No breaking change
=> fix(database): fix mongoose migration to 6.x

src/whisp/whisp.resolver.ts
Bug fix
Subscription is not working
Subscription is working back
No
=> fix(subscription): fix auth issue

schema.gql, src/app.module.ts, src/auth/connection-params.ts, src/auth/gql-context.ts, src/auth/gql-jwt-auth.guard.ts, src/whisp/whisp.resolver.ts, tests/e2e/app/app.e2e-spec.ts, tests/e2e/health/health.e2e-spec.ts
Feature subscription required auth
subscription is working without authorization
subscription is working only with  authorization token provided
No
=> feat(subscription): jwt auth for subscription

Dockerfile.aws, docker-compose.yml, docs/security.md, package-lock.json, package.json, src/app.controller.ts, src/auth/jwt.strategy.ts, src/config/config.service.ts, tests/unit/app.controller.spec.ts, tests/unit/config/config.service.spec.ts
upgrade passport-multi-jwt to version 1.0.0 containing passthrough feature
can't change passport-multi-jwt configuration to disabled authentication
adding passthrough:true to passport-multi-jwt configuration disable authentication
NO
=> feat(authentication): passthrough

.github/workflows/ci.yml
=> chore: upgrade ubuntu runner version on release job

src/whisp/whisp.resolver.ts, src/whisp/whisp.service.ts
=> feat(WEB-2070): WEB-2070 added log statements to check errors

.github/workflows/ci.yml, src/whisp/whisp.resolver.ts, src/whisp/whisp.service.ts, tests/unit/whisp/whisp.service.spec.ts
Bug fix
Subscription has errors on new whisp creation
Subscription does not produce error on new whisp creation
=> feat(WEB-2070): WEB-2070 Wait for db write on whisp create

src/whisp/whisp.service.ts
=> feat(WEB-2070): WEB-2070 use primary replica set for subscription callback queries

src/whisp/whisp.service.ts
=> fix(WEB-2070): WEB-2070 added comments for db node change

src/config/config.service.ts
=> fix: WEB-2246 remove some mongoose options

src/config/config.service.ts
=> fix: WEB-2246 parse pool size

src/app.module.ts, src/config/config.service.ts, src/whisp/whisp.service.ts
=> fix: WEB-2246 remove reading primary replica

tests/integration/whisp/whisp.service.int-spec.ts, tests/unit/whisp/whisp.service.spec.ts
=> fix: WEB-2336 added test cases for data index changes

docs/models/whisp.md
=> chore: WEB-2336 data index key documentation update

src/whisp/whisp.service.ts
=> feat: WEB-2335 Proxy decom test

src/whisp/whisp.service.ts
=> feat: WEB-2335 Proxy decom test release without proxy and different docker file

src/whisp/whisp.service.ts
=> feat: WEB-2355 increase version

.releaserc
=> feat: WEB-2355 prepare cmd update

Dockerfile.aws
=> feat: WEB-2355 Trigger new version
